services:
  browser:
    # It is recommended to use full tag(in this case is 131.0) to pin a specific browser instead of latest
    image: selenium/standalone-chromium:latest
    shm_size: '2g'
    ports:
      - "4444:4444"  # Default port for Selenium WebDriver

  tests-container:
    build: .
    depends_on:
      - browser
    environment:
      - SELENIUM_HOST=browser
      - SELENIUM_PORT=4444